"""Build index.html (standalone page for GitHub Pages) from library-passport.html.

library-passport.html is the Artifact source: page content without the
<!doctype>/<html>/<head>/<body> skeleton, which claude.ai adds at publish time.
This wraps it in that skeleton so it also runs as a plain web page.

Run after editing library-passport.html:  python3 build_index.py
"""
from pathlib import Path

here = Path(__file__).parent
src = (here / "library-passport.html").read_text(encoding="utf-8")

split = src.index("</style>") + len("</style>")
head, body = src[:split], src[split:]

reset = (
    "<style>:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);"
    "padding-bottom:env(safe-area-inset-bottom,0px)}body{margin:0}"
    "img{max-width:100%}[hidden]{display:none!important}</style>\n"
)

page = (
    "<!doctype html>\n<html lang=\"en\">\n<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
    "<!-- Generated by build_index.py from library-passport.html. Edit that file, not this one. -->\n"
    + reset + head.strip() + "\n</head>\n<body>\n" + body.strip() + "\n</body>\n</html>\n"
)
(here / "index.html").write_text(page, encoding="utf-8")
print(f"index.html written ({len(page):,} bytes)")
